logging:
  level:
    org:
      springframework:
        web: DEBUG
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_example
    username: nimisha
    password: bnnair
    platform: mysql
    initialization-mode: never
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://demo-mysql:3306/todo_example
    username: nimisha
    password: bnnair
    initialization-mode: always
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
